// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCfsTJNA9zb4eQwFjlTsc-TLlTNTWKh94',
    appId: '1:240282659615:web:f3ef10efcf32aae625de2a',
    messagingSenderId: '240282659615',
    projectId: 'echonest-f282b',
    authDomain: 'echonest-f282b.firebaseapp.com',
    storageBucket: 'echonest-f282b.appspot.com',
    measurementId: 'G-R00P675Q2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JSGWkDBd58wkMN4Y1nFHpkVIYQtI01g',
    appId: '1:240282659615:android:1ad025aec72cf1a325de2a',
    messagingSenderId: '240282659615',
    projectId: 'echonest-f282b',
    storageBucket: 'echonest-f282b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKbX0ueuS_uKmooe09YKwF94Amsss67I',
    appId: '1:240282659615:ios:649dc7066814d67f25de2a',
    messagingSenderId: '240282659615',
    projectId: 'echonest-f282b',
    storageBucket: 'echonest-f282b.appspot.com',
    iosBundleId: 'com.example.echonest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJKbX0ueuS_uKmooe09YKwF94Amsss67I',
    appId: '1:240282659615:ios:12cc5317f31da21025de2a',
    messagingSenderId: '240282659615',
    projectId: 'echonest-f282b',
    storageBucket: 'echonest-f282b.appspot.com',
    iosBundleId: 'com.example.echonest.RunnerTests',
  );
}
